export const endpointMap = {
  batch: '',
  imprestTypes: "/api/KineticTechnology/CashMgt/v2.0/imprestTypeApi",
  currencies: "/api/KineticTechnology/Payroll/v2.0/currencies",
  dimensions: "/api/KineticTechnology/CashMgt/v2.0/dimensionValuesApi",
  expenseCodes: "/api/KineticTechnology/CashMgt/v2.0/expenseCodes",
  projectActivities: "/api/kinetics/timeSheet/v1.0/projects",
  modesOfTransport: "/api/KineticTechnology/CashMgt/v2.0/modeOfTransport",
  unitsOfMeasure: "/api/v2.0/unitsOfMeasure",
  dimensionSpeedKeys: "/api/KineticTechnology/Amber/v1.0/dimensionSpeedKeyApi",
  projects: "/api/kinetics/timeSheet/v1.0/projects",
  approvalEntries: "/api/Kinetics/VOYAGER/v1.0/approvalEntries",
  approvalEntry: "/api/kinetics/voyager/v1.0/approvalEntriesReport",
  approvalAttachments: "/api/kinetics/voyager/v1.0/documentAttachments",
  paymentMethods: "/api/KineticTechnology/Payroll/v2.0/paymentMethod",
  banks: "/api/KineticTechnology/PayRoll/v2.0/banks",
  bankBranches: "/api/KineticTechnology/PayRoll/v2.0/bankBranches",
  SendAdvanceForApproval: "/ODATAV4/CashManagement_SendApprovalRequest",
  CancelAdvanceApprovalRequest: "/ODATAV4/CashManagement_CancelApprovalRequest",
  AdvnaceLiquidation: "/ODATAV4/CashManagement_LiquidateImprest",
  requisitionDimensions: "/api/kinetics/requisition/v1.0/dimensionValues",
  billingItems: "/api/kinetics/requisition/v1.0/billingItems",
  locations: "/api/kinetics/requisition/v1.0/locations",
  employees: "/api/KineticTechnology/ESS/v1.0/leavemployees",
  SendRequisitionForApproval: "/ODataV4/Requisition_SendApprovalRequest",
  CancelRequisitionApprovalRequest:
    "/ODataV4/Requisition_CancelApprovalRequest",
  salaryAdvance: "/api/KineticTechnology/PayRoll/v2.0/payrollAdvance",
  advance: "/api/KineticTechnology/CashMgt/v2.0/imprestApi",
  GetRequisitionStats: "/ODataV4/Requisition_getRequisitionStats",
  employeeBanks: "/api/KineticTechnology/Payroll/v2.0/employeeBanks",
  payrollPeriods: "/api/KineticTechnology/Payroll/v2.0/payrollPeriods",
  imprest: "/api/KineticTechnology/CashMgt/v2.0/imprestApi",
  imprestLine: "/api/KineticTechnology/CashMgt/v2.0/imprestLinesAPI",
  cashManagementAttachment: "/api/KineticTechnology/CashMgt/v2.0/attachments",
  imprestDetailedLine: "/api/KineticTechnology/CashMgt/v2.0/detailedImprestLines",
  requisitions: "/api/kinetics/requisition/v1.0/requisitions",
  delegateApproval: "/ODataV4/ApprovalsManagement_delegateDoc",
  approveDocument: "/ODataV4/ApprovalsManagement_approveDoc",
  rejectApprovalDocument: "/ODataV4/ApprovalsManagement_rejectDoc",
  createTravelAdvanceFromTravel: "/ODataV4/TravelManager_createImprest",
  purposeOfTravel: "/api/kinetics/adminTravel/v1.0/purposeOfTravel",
} as const;

export const memoryMap: Map<string, any> = new Map(Object.entries(endpointMap));
export type ENDPOINTMAP = keyof typeof endpointMap;
