export const endpointMap = {
  batch: "",
  imprestTypes: "/api/KineticTechnology/CashMgt/v2.0/imprestTypeApi",
  currencies: "/api/KineticTechnology/Payroll/v2.0/currencies",
  globalCurrencies: "api/v2.0/currencies",
  dimensions: "/api/KineticTechnology/CashMgt/v2.0/dimensionValuesApi",
  expenseCodes: "/api/KineticTechnology/CashMgt/v2.0/expenseCodes",
  projectActivities: "/api/kinetics/timeSheet/v1.0/projects",
  modesOfTransport: "/api/KineticTechnology/CashMgt/v2.0/modeOfTransport",
  unitsOfMeasure: "/api/v2.0/unitsOfMeasure",
  dimensionSpeedKeys: "/api/KineticTechnology/Amber/v1.0/dimensionSpeedKeyApi",
  projects: "/api/kinetics/timeSheet/v1.0/projects",
  approvalEntries: "/api/Kinetics/VOYAGER/v1.0/approvalEntries",
  approvalEntry: "/api/kinetics/voyager/v1.0/approvalEntriesReport",
  approvalAttachments: "/api/kinetics/voyager/v1.0/documentAttachments",
  paymentMethods: "/api/KineticTechnology/Payroll/v2.0/paymentMethod",
  banks: "/api/KineticTechnology/PayRoll/v2.0/banks",
  bankBranches: "/api/KineticTechnology/PayRoll/v2.0/bankBranches",
  SendAdvanceForApproval: "/ODATAV4/CashManagement_SendApprovalRequest",
  CancelAdvanceApprovalRequest: "/ODATAV4/CashManagement_CancelApprovalRequest",
  AdvnaceLiquidation: "/ODATAV4/CashManagement_LiquidateImprest",
  requisitionDimensions: "/api/kinetics/requisition/v1.0/dimensionValues",
  billingItems: "/api/kinetics/requisition/v1.0/billingItems",
  locations: "/api/kinetics/requisition/v1.0/locations",
  employees: "/api/KineticTechnology/ESS/v1.0/leavemployees",
  SendRequisitionForApproval: "/ODataV4/Requisition_SendApprovalRequest",
  CancelRequisitionApprovalRequest:
    "/ODataV4/Requisition_CancelApprovalRequest",
  salaryAdvance: "/api/KineticTechnology/PayRoll/v2.0/payrollAdvance",
  advance: "/api/KineticTechnology/CashMgt/v2.0/imprestApi",
  employeeBanks: "/api/KineticTechnology/Payroll/v2.0/employeeBanks",
  payrollPeriods: "/api/KineticTechnology/Payroll/v2.0/payrollPeriods",
  imprest: "/api/KineticTechnology/CashMgt/v2.0/imprestApi",
  imprestLine: "/api/KineticTechnology/CashMgt/v2.0/imprestLinesAPI",
  cashManagementAttachment: "/api/KineticTechnology/CashMgt/v2.0/attachments",
  imprestDetailedLine:
    "/api/KineticTechnology/CashMgt/v2.0/detailedImprestLines",
  delegateApproval: "/ODataV4/ApprovalsManagement_delegateDoc",
  approveDocument: "/ODataV4/ApprovalsManagement_approveDoc",
  rejectApprovalDocument: "/ODataV4/ApprovalsManagement_rejectDoc",
  createTravelAdvanceFromTravel: "/ODataV4/TravelManager_createImprest",
  purposeOfTravel: "/api/kinetics/adminTravel/v1.0/purposeOfTravel",
  travelProfile: "/api/kinetics/adminTravel/v1.0/userProfiles",
  userProfiles: "/api/kinetics/enigma/v1.0/userProfiles",
  profileDependants: "/api/kinetics/adminTravel/v1.0/profileDependants",
  travelRequests: "/api/kinetics/adminTravel/v1.0/travelRequests",
  countries: "/api/kinetics/adminTravel/v1.0/countriesRegions",
  cities: "/api/kinetics/enigma/v1.0/postCodes",
  modeOfTransport: "/api/KineticTechnology/CashMgt/v2.0/modeOfTransport",
  travelRoutes: "/api/kinetics/adminTravel/v1.0/travelRequestRoutes",
  perDiemAllotments: "/api/kinetics/adminTravel/v1.0/perDiemAllotments",
  sendTravelRequestForApproval:
    "/ODataV4/TravelManager_sendTravelRequestForApproval",
  cancelTravelRequestApprovalRequest:
    "/ODataV4/TravelManager_cancelTravelRequestApprovalRequest",
  travellerChecklist: "/api/kinetics/adminTravel/v1.0/travellerChecklist",
  travellers: "/api/kinetics/adminTravel/v1.0/travellers",
  genders: "/api/kinetics/enigma/v1.0/genders",
  profileTitles: "/api/kinetics/enigma/v1.0/profileTitles",
  travelAttachments: "/api/kinetics/adminTravel/v1.0/attachments",
  visaApplications: "/api/kinetics/adminTravel/v1.0/visaApplications",
  visaApplicationLines: "/api/kinetics/adminTravel/v1.0/visaApplicationLines",
  travelRequestProviders:
    "/api/kinetics/adminTravel/v1.0/travelRequestProviders",
  getBTACertificate: "/ODataV4/TravelManager_getBTACertificate",
  getIntroductoryLetter: "/ODataV4/TravelManager_getIntroductoryLetter",
  travel_attachments: "/api/kinetics/adminTravel/v1.0/attachments",
  stageDocumentChecklist:
    "/api/kinetics/adminTravel/v1.0/stageDocumentChecklist",
  submitVisitorTravelRequest: "/ODataV4/TravelManager_submitTravelRequest",
  missionTypes: "/api/KineticTechnology/CashMgt/v2.0/missionTypes",
  travelRequestLine: "/api/kinetics/adminTravel/v1.0/travelRequestLines",
  getLetterOfInvitation1: "/ODataV4/TravelManager_getLetterOfInvitation1",
  getLetterOfInvitation2: "/ODataV4/TravelManager_getLetterOfInvitation2",
  getRequisitionStats: "/ODataV4/Requisition_getRequisitionStats",
  requisitions: "/api/kinetics/requisition/v1.0/requisitions",
  requisitionLines: "/api/kinetics/requisition/v1.0/requisitionLines",
  sendRequisitionForApproval: "/ODataV4/Requisition_getRequisitionStats",
  cancelRequisitionApprovalRequest: "/ODataV4/Requisition_CancelApprovalRequest",
} as const;

export const memoryMap: Map<string, any> = new Map(Object.entries(endpointMap));
export type ENDPOINTMAP = keyof typeof endpointMap;
